# TODO : Make this work
- name: Clone GGA repository
  git:
    repo: "{{ repo_name }}"
    dest: "{{ repo_folder }}"
    version: "{{ gga_load_data_version }}"
    accept_hostkey: yes
    force: yes
    recursive: no
#    update: yes

- name: Installing python libraries
  pip:
    requirements: /opt/gga_load_data/requirements.txt

- name: Run gga_init script
  script: gga_init.py
  args:
    chdir: /opt/gga_load_data

- name: Run gga_load_data script
  script: gga_load_data.py
  args:
    chdir: /opt/gga_load_data
