- name: Include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Include os specific tasks
  include: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"

- name: Clone GGA repository
  git:
    repo: "{{ repo_name }}"
    dest: "{{ repo_folder }}"
    version: "{{ gga_load_data_version }}"
    accept_hostkey: yes
    force: yes
    recursive: no
#    update: yes

- name: Installing python libraries
  pip:
    executable: pip3
    requirements: "{{ repo_folder }}/requirements.txt"

# Copy config files into /opt/gga_load_data ?

- name: Run gga_init script
  command: "python3 {{ gga_init }} {{ input_sp }} -c {{ config_file }}"
  args:
    chdir: "{{ repo_folder }}"

- name: Run gga_load_data script
  command: "python3 {{ gga_load_data }} {{ input_sp }} -c {{ config_file }}"
  args:
    chdir: "{{ repo_folder }}"
