# TODO : Make this work
- name: Clone GGA repository
  git:
    repo: "{{ repo_name }}"
    dest: "{{ repo_folder }}"
    version: "{{ gga_load_data_version }}"
    accept_hostkey: yes
    force: yes
    recursive: no
#    update: yes

#- name: Installing python libraries
#  pip:
#    requirements: /home/fr2424/sib/rdallet/Projets/GGA_Cloud/ansible/gga_load_data/requirements.txt

#- name: Run gga_load_data script
