- name: Clone GGA repository
  git:
    repo: "{{ repo_name }}"
    dest: "{{ repo_folder }}"
    version: "{{ gga_load_data_version }}"
    accept_hostkey: yes
    force: yes
    recursive: no
#    update: yes

- name: Installing python libraries
  pip:
    executable: pip3
    requirements: "{{ repo_folder }}/requirements.txt"

- name: Run gga_init script
  script: "{{ gga_init }}"
  args:
    chdir: "{{ repo_folder }}"

- name: Run gga_load_data script
  script: "{{ gga_load_data }}"
  args:
    chdir: "{{ repo_folder }}"
