---
roles:
  - src: geerlingguy.git
    version: 3.0.0
  - src: geerlingguy.docker
    version: 3.0.0

collections:
  - name: community.general
    version: 1.3.2
    source: https://galaxy.ansible.com

