---
roles:
  - src: andrewrothstein.terraform
    version: v2.2.53
  - src: geerlingguy.git
    version: 3.0.0
  - src: geerlingguy.docker
    version: 2.9.0

collections:
  - name: community.general
    version: 1.3.2
    source: https://galaxy.ansible.com

