---

# GGA automation scripts repository
repo_name: http://gitlab.sb-roscoff.fr/abims/e-infra/gga_load_data.git

# Path where to clone the repository
repo_folder: /opt/gga_load_data

# Scripts name
gga_init: gga_init.py
gga_load_data: gga_load_data.py
gga_load_data_version: v1.0.2

# Config files for GGA scripts
config_file: config_example.yml
input_sp: input_example.yml

# Name of the organism for the directory tree structure
genus_sp: citrus_sinensis
