- hosts: localhost
  connection: local
  become: yes
  become_user: root
  roles:
    - cluster_software
    - geerlingguy.git
    - geerlingguy.docker    
  tasks:
  - name: Installing python libraries
    pip:
      requirements: /home/fr2424/sib/rdallet/Projets/GGA_Cloud/ansible/gga_load_data/requirements.txt