- hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars:
    docker_edition: "ce"
    docker_version: "19.03"
  roles:
    - nickjj.docker
    - mdklatt.python3
  tasks:
  - name: Installing python libraries
    pip:
      chdir: "~/Projets/GGA_Cloud/ansible/gga_load_data/"
      requirements: requirements.txt
