- hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars:
    docker_edition: "ce"
    docker_version: "19.03"
  roles:
    - nickjj.docker
    - mdklatt.python3
  tasks:
  - name: Installing python libraries
    pip:
      name: 
        - pandas
        - pyyaml
        - bioblend>=0.13
