---
- name: Install requirements for package install
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
  when: python3_pyenv == None
  become: true


- name: Install system packages required for pyenv
  apt:
    name:
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - make
      - zlib1g-dev
    state: present
  when: python3_pyenv != None
  become: true
