#- name: Container present
#  community.docker.docker_container:
    # Get name auto
#    name: citrus_sinensis_galaxy.1.6cbgzj16lznsc4br334l5upp6
#    image: quay.io/galaxy-genome-annotation/docker-galaxy-annotation:gmod
#    state: present
#  register: galaxy_status

#- name: Get galaxy container IP
#  set_fact:
#    container_ip: "{{ galaxy_status.ansible_facts.docker_container.NetworkSettings.IPAddress }}"

#- name: Check container status
#  wait_for:
#    host: "{{ container_ip }}"
#    port: 8888

- name: Run gga_load_data script
  command: "python3 {{ gga_load_data }} {{ input_sp }} --config {{ config_file }}"
  args:
    chdir: "{{ repo_folder }}"
