# Copy config files
- name: Copy configuration file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ config_file }}"
    dest: "{{ repo_folder }}"

- name: Copy input species file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ input_sp }}"
    dest: "{{ repo_folder }}"

# Initialize GGA
- name: Run gga_init script
  command: "python3 {{ gga_init }} {{ input_sp }} --config {{ config_file }}"
  args:
    chdir: "{{ repo_folder }}"
