# This is the configuration file used by the gga_init.py, gga_load_data.py and run_workflow.py scripts
# It contains (sensible) variables to set up different docker services and should not be committed when filled

# "all" section contains variables used by several services at once or the paths to import sensible files that cannot be procedurally generated/formatted using the scripts
all:
      # The hosting machine name
      hostname: localhost
      dashboard_port: 8001
      http_port: 8888
      https_port: 8889
      # IP of the upstream proxy (for traefik)
      proxy_ip: XXXXXXXXXXXX
      auth_hostname: XXXXXXXXXXXX
      # Path to the custom authelia configuration file (j2 template)
      authelia_config_path: /path/to/authelia_config.yml.j2 
# galaxy-specific environment variables
galaxy:
      galaxy_default_admin_email: gga@galaxy.org
      galaxy_defaut_admin_user: gga
      galaxy_default_admin_password: password
      galaxy_config_master_api_key: master
      webapollo_user: admin_apollo@galaxy.org
      webapollo_password: apollopass
# tripal-specific variables
tripal:
      # Tripal database password (also used by galaxy as an environment variable)
      tripal_password: tripalpass
      # Custom banner path
      banner_path: /home/fr2424/sib/alebars/projects/gga_load_data/misc/banner.png
      # Use this to use another theme
      tripal_theme_name: abims
      # Use this to install another theme (cannot be named custom_theme_git_clone currently)
      tripal_theme_git_clone: http://gitlab.sb-roscoff.fr/abims/e-infra/tripal_abims.git
