# This is the configuration template file used by the gga_init.py, gga_load_data.py and run_workflow.py scripts

# "all" section contains variables used by several services at once or the paths to import sensitive files
all:
      hostname: localhost  # Required. The hosting machine name
      dashboard_port: 8001  # Required. The desired port (on the hosting machine) for the traefik container dashboard
      http_port: 8888  # Required. The HTTP port docker will use on the hosting machine 
      #https_port: 8889  # Required for Authelia. The HTTPS port docker will use on the hosting machine
      proxy_ip: 192.168.101.117  # Required. IP of the upstream proxy (used by Traefik)
      #authentication_domain_name: XXXXXXXXXXXX  #  Required for Authelia. The authentication domain name.
      #authelia_config_path: /path/to/authelia_config.yml #  Required for Authelia. Path to the Authelia configuration file
# galaxy-specific variables
galaxy:
      galaxy_default_admin_email: gga@galaxy.org  # Required
      galaxy_defaut_admin_user: gga  # Required
      galaxy_default_admin_password: password  # Required
      webapollo_user: admin_apollo@galaxy.org  # Required
      webapollo_password: apollopass  # Required
      galaxy_config_remote_user_maildomain: mydomain.com  # Required. The maildomain used by Galaxy authentication
      persist_galaxy_data: "False"  # Optional (default: True). If False, docker data will NOT be persisted on your host's file system and will be lost any time the galaxy container is recreated. Do not set this variable to "False" for production
# tripal-specific variables
tripal:
      tripal_password: tripalpass  # Required. Tripal database password (also used by galaxy as an environment variable)
      #banner_path: /my/path/banner.png  # Optional. Custom banner path 
      #tripal_theme_name: tripal_gga   # Optional. Use this to use another theme
      #tripal_theme_git_clone: http://gitlab.sb-roscoff.fr/abims/e-infra/tripal_gga.git  # Optional. Use this to install another theme.
# jbrowse-specific variables
jbrowse:
      menu_url: "http://localhost:8888/" # Optional. Used with run_workflow_phaeoexplorer.py: if present, this variable is used to define JBrowse menu_url (to define the template url for the JBrowse feature's link to Tripal), if absent, will use default "https://hostname"
