# This is the configuration file used by the gga_init.py, gga_load_data.py and run_workflow.py scripts
# It contains (sensible) variables to set up different docker services

# "all" section contains variables used by several services at once or the paths to import sensible files that cannot be procedurally generated/formatted using the scripts
all:
      custom_host: localhost  # The hosting machine name
      custom_authelia_config_path: /path/to/your/authelia/config  # The path to the authelia config yml to use, an example is available in the "examples" folder at the repo root
# "galaxy" section contains variables used to set up the galaxy service
galaxy:
      custom_galaxy_default_admin_email: admin@galaxy.org  # The default admin email (used to connect to the instance)
      custom_galaxy_defaut_admin_user: admin  # The default admin user
      custom_galaxy_default_admin_password: password  # The default admin password (used to connect to the instance)
      custom_galaxy_config_master_api_key: master  # The master API key (not in use at the moment so you can skip this)
      custom_galaxy_tripal_password: galaxy_tripal_password  # Same as custom_tripal_admin_password (connection to db relies on this)
      custom_galaxy_web_apollo_user: admin_apollo@galaxy.org  # Apollo user
      custom_galaxy_web_apollo_password: galaxy_apollo_password  # Apollo password tied to the user above
tripal:
      custom_tripal_admin_password: galaxy_tripal_password  # Same as custom_galay_tripal_password (connection to db relies on this)
      custom_banner: /path/to/banner  # Custom banner, TODO: defaults to a generic banner
      custom_theme: "abims_gga"   # Use this to use another theme
      custom_theme_git_clone: "http://gitlab.sb-roscoff.fr/abims/e-infra/tripal_gga.git"  # Use this to install another theme than the default one
